server:
    port: 0


spring:
    config:
        import: optional:configserver:http://localhost:8888
    application:
        name: auth-service
    profiles:
        active: dev


    output:
        ansi:
            enabled: always
    datasource:
        url: jdbc:postgresql://localhost:5432/sp_auth
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
    level:
        root: info