server:
    port: 0


spring:
    config:
        import: optional:configserver:http://localhost:8888
    application:
        name: auth-service
    profiles:
        active: dev


    output:
        ansi:
            enabled: always
    datasource:
        url: jdbc:postgresql://localhost:5432/sp_auth
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        timeout: 60000
logging:
    level:
        root: info
    pattern:
            level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

twilio:
    account:
        sid: AC0dac0d82def301d3eda275ca6c9b90c5
    auth:
        token: d05aec82e72ae63edd198e3a3317b5a6
    phone:
        number: +14253639525

