version: "3.7"
services:
    zipkin:
        container_name: zipkin
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
    config-service:
        image: sp/config-service:1.1-SNAPSHOT
        ports:
            - "8088:8088"
        healthcheck:
            test: curl --fail http://localhost:8088/posts/docker || exit 1
            interval: 5s
            timeout: 2s
            retries: 3
    eureka-service:
        image: sp/eureka-service:1.1-SNAPSHOT
        ports:
            - "8061:8061"
        depends_on:
            config-service:
                condition: service_healthy
        links:
            - config-service
        healthcheck:
            test: curl --fail http://localhost:8761/eureka/v2/apps || exit 1
            interval: 4s
            timeout: 2s
            retries: 3
        environment:
            SPRING_PROFILES_ACTIVE: docker
    post-service:
        image: sp/post-service:1.2-SNAPSHOT
        ports:
            - "8080"
        depends_on:
            eureka-service:
                condition: service_healthy
        links:
            - config-service
            - eureka-service
            - zipkin
        environment:
            SPRING_PROFILES_ACTIVE: docker
    user-post-service:
        image: sp/user-post-service:1.2-SNAPSHOT
        ports:
            - "8080"
        depends_on:
            eureka-service:
                condition: service_healthy
        links:
            - config-service
            - eureka-service
            - post-service
            - zipkin
        environment:
            SPRING_PROFILES_ACTIVE: docker
    gateway-service:
        image: sp/gateway-service:1.1-SNAPSHOT
        ports:
            - "8762:8762"
        depends_on:
            eureka-service:
                condition: service_healthy
        environment:
            SPRING_PROFILES_ACTIVE: docker
        links:
            - config-service
            - eureka-service
            - post-service
            - user-post-service
            - zipkin