server:
    port: 0
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
spring:
    application:
        name: user-post-service
    output:
        ansi:
            enabled: always

    cloud:
        openfeign:
            circuitbreaker:
                enabled: true
                alphanumeric-ids:
                        enabled: true

#resilience4j:
#    circuitbreaker:
#        instances:
#            PostServiceClient_getUserPosts_String:
#            register-health-indicator: true
#            slidingWindowSize: 5
#            failureRateThreshold: 50
#            waitDurationInOpenState: 3000ms
#            slowCallRateThreshold: 50
#            slowCallDurationThreshold: 200ms

resilience4j:
    circuitbreaker:
        configs:
            default:
                registerHealthIndicator: true
        instances:
            PostServiceClient:
#                slidingWindowType: count
                minimumNumberOfCalls: 10
                failureRateThreshold: 50
                slowCallRateThreshold: 50
                slowCallDurationThreshold: 200ms
                automaticTransitionFromOpenToHalfOpenEnabled: true
                permittedNumberOfCallsInHalfOpenState: 5
                waitDurationInOpenState: 3000ms

management:
    health:
        circuitbreakers:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always
