server:
    port: 8762
spring:
    application:
        name: gateway-service
    main:
        web-application-type: reactive
        allow-bean-definition-overriding: true
    output:
        ansi:
            enabled: always
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                -   id: auth-service
                    uri: lb://auth-service
                    predicates:
                        - Path=/auth/**
                    filters:
                        - RewritePath=/auth/(?<path>.*), /$\{path}
                -   id: user-post-service
                    uri: lb://user-post-service
                    predicates:
                        - Path=/users/**
                    filters:
                        - RewritePath=/users/(?<path>.*), /$\{path}
                -   id: post-service
                    uri: lb://post-service
                    predicates:
                        - Path=/posts/**
                    filters:
                        - RewritePath=/posts/(?<path>.*), /$\{path}
                -   id: openapi
                    uri: http://localhost:${server.port}
                    predicates:
                        - Path=/v3/api-docs/**
                    filters:
                        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
            httpclient:
                response-timeout: 30
springdoc:
    swagger-ui:
        urls:
            -   name: posts
                url: /v3/api-docs/posts
            -   name: users
                url: /v3/api-docs/users
logging:
    level:
        root: debug